/**
 * Created by s.evdokimov on 03.01.2017.
 */

export const MODAL_EDIT_SHOW = 'MODAL_EDIT_SHOW';
export const MODAL_EDIT_HIDE = 'MODAL_EDIT_HIDE';

export const MODAL_CREATE_SHOW = 'MODAL_CREATE_SHOW';
export const MODAL_CREATE_HIDE = 'MODAL_CREATE_HIDE';

export const MODAL_CONFIRM_SHOW = 'MODAL_CONFIRM_SHOW';
export const MODAL_CONFIRM_HIDE = 'MODAL_CONFIRM_HIDE';

export const MODAL_UPLOAD_SHOW = 'MODAL_UPLOAD_SHOW';
export const MODAL_UPLOAD_HIDE = 'MODAL_UPLOAD_HIDE';
export const MODAL_UPLOAD_FILE = 'MODAL_UPLOAD_FILE';

export const MODAL_ALL_HIDE = 'MODAL_ALL_HIDE';
